import type { Metadata } from "next";
// import { Schibsted_Grotesk, Martian_Mono } from "next/font/google";
import { Lexend } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const lexend = Lexend({
  subsets: ["latin"],
});

// const martianMono = Martian_Mono({
//   variable: "--font-martian-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "3K Home Myspace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.className} antialiased`}
      >
        <Navbar />

        <main>
          {children}
        </main>

      </body>
    </html>
  );
}
